services:
  app:
    build:
      context: ./backend
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: telecare_app
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: production
      PORT: 4001
      DB_HOST: db
      DB_PORT: 5432
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      REDIS_URL: redis://redis:6379
    env_file:
      - .env
    depends_on:
      - db
      - mailpit
      - redis

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install --include=dev && npm run build && npm run start"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - app

  mailpit:
    image: axllent/mailpit:latest
    container_name: telecare_mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  db:
    image: postgres:16-alpine
    container_name: telecare_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: telecare_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
