// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { defineConfig, env } from 'prisma/config';

// Load env from project root .env if present; otherwise fall back to default lookup.
const rootEnvPath = path.resolve(__dirname, '..', '.env');
if (fs.existsSync(rootEnvPath)) {
    dotenv.config({ path: rootEnvPath });
} else {
    dotenv.config();
}

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    engine: 'classic',
    datasource: {
        url: env('DATABASE_URL'),
    },
});
